Repository hngi/mobileforce-afrivac, pull requests merged in 2020-07, with the labels that each got.

#279 feat and fix: #226
  app/src/main/java/com/michael/afrivac/MainActivity.java
  app/src/main/java/com/michael/afrivac/model/AskedQuestions.java
Labels: 2 P

#293 Test
  app/src/main/res/layout/activity_support_page.xml
  app/src/main/res/layout/fragment_support.xml
Labels: 1 P

#288 Fixes: #286
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/michael/afrivac/Adapter/ViewRoomsAdapter.java
  app/src/main/java/com/michael/afrivac/ViewRoomsActivity.java
  app/src/main/res/drawable/ic_baseline_free_breakfast_24.xml
  app/src/main/res/drawable/ic_baseline_hot_tub_24.xml
  app/src/main/res/drawable/ic_baseline_room_service_24.xml
  app/src/main/res/drawable/ic_baseline_wifi_12.xml
  app/src/main/res/drawable/ic_favorite_border_white_24dp.xml
  app/src/main/res/drawable/loading_profile_image.png
  app/src/main/res/layout/view_more_rooms_1.xml
  app/src/main/res/layout/view_more_rooms_recycler_items.xml
  app/src/main/res/values/strings.xml
Labels: 2 P

#305 feat and fix: #263
  app/src/main/java/com/michael/afrivac/Adapter/AskedQuestionsAdapter.java
  app/src/main/java/com/michael/afrivac/MainActivity.java
  app/src/main/java/com/michael/afrivac/ui/support/SupportFragment.java
  app/src/main/res/layout/fragment_support.xml
  app/src/main/res/layout/support_page_recycler_list_item.xml
Labels: 1 P

#302 Fixes #265
  .idea/jarRepositories.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/michael/afrivac/Auth/AuthViewModel.java
  app/src/main/java/com/michael/afrivac/CustomViewPager.java
  app/src/main/java/com/michael/afrivac/LoginActivity.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsActivity.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsHotelsAdapter.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsOverviewFragment.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsRecreationCentersAdapter.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsReviewFragment.java
  app/src/main/java/com/michael/afrivac/PopularDestinationReviewsRecyclerviewAdapter.java
  app/src/main/java/com/michael/afrivac/PopularDestinationSliderAdapter.java
  app/src/main/java/com/michael/afrivac/UserReviewDetails.java
  app/src/main/java/com/michael/afrivac/ui/home/HomeFragment.java
  app/src/main/java/com/michael/afrivac/ui/popular_destination/PopularDestinationFragment.java
  app/src/main/java/com/michael/afrivac/ui/popular_destination/PopularDestinationRVAdapter.java
  app/src/main/res/drawable-mdpi/cairo_img.png
  app/src/main/res/drawable-v24/hotel1_img.png
  app/src/main/res/drawable-v24/hotel2_img.png
  app/src/main/res/drawable-v24/img_what_to_do1.png
  app/src/main/res/drawable-v24/img_what_to_do2.png
  app/src/main/res/drawable-v24/img_what_to_do3.png
  app/src/main/res/drawable-v24/photo2.png
  app/src/main/res/drawable-v24/photo3.png
  app/src/main/res/drawable-v24/photos1.png
  app/src/main/res/drawable/airline_sit.xml
  app/src/main/res/drawable/default_dot.xml
  app/src/main/res/drawable/round_trip_icon.xml
  app/src/main/res/drawable/selected_dot.xml
  app/src/main/res/drawable/tab_selector.xml
  app/src/main/res/drawable/white_back_arrow.xml
  app/src/main/res/drawable/white_bg_blue_stroke.xml
  app/src/main/res/layout/activity_popular_destination_details.xml
  app/src/main/res/layout/fragment_location_activity_reviews.xml
  app/src/main/res/layout/fragment_popular_destination_details_overview.xml
  app/src/main/res/layout/fragment_popular_destination_details_review.xml
  app/src/main/res/layout/popular_destination_details_recreation_recyclerview_item.xml
  app/src/main/res/layout/popular_destination_recyclerview_hotels_item.xml
  app/src/main/res/layout/popular_destination_reviews_recyclerview_item.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: 2 P, 3 P

#307 Test
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/michael/afrivac/Adapter/AskedQuestionsAdapter.java
  app/src/main/java/com/michael/afrivac/Adapter/ViewRoomsAdapter.java
  app/src/main/java/com/michael/afrivac/CustomViewPager.java
  app/src/main/java/com/michael/afrivac/MainActivity.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsActivity.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsHotelsAdapter.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsOverviewFragment.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsRecreationCentersAdapter.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsReviewFragment.java
  app/src/main/java/com/michael/afrivac/PopularDestinationReviewsRecyclerviewAdapter.java
  app/src/main/java/com/michael/afrivac/PopularDestinationSliderAdapter.java
  app/src/main/java/com/michael/afrivac/UserReviewDetails.java
  app/src/main/java/com/michael/afrivac/ViewRoomsActivity.java
  app/src/main/java/com/michael/afrivac/ui/account/AccountFragment.java
  app/src/main/java/com/michael/afrivac/ui/home/HomeFragment.java
  app/src/main/java/com/michael/afrivac/ui/popular_destination/PopularDestinationFragment.java
  app/src/main/java/com/michael/afrivac/ui/popular_destination/PopularDestinationRVAdapter.java
  app/src/main/java/com/michael/afrivac/ui/support/SupportFragment.java
  app/src/main/res/drawable-mdpi/cairo_img.png
  app/src/main/res/drawable-v24/hotel1_img.png
  app/src/main/res/drawable-v24/hotel2_img.png
  app/src/main/res/drawable-v24/img_what_to_do1.png
  app/src/main/res/drawable-v24/img_what_to_do2.png
  app/src/main/res/drawable-v24/img_what_to_do3.png
  app/src/main/res/drawable-v24/photo2.png
  app/src/main/res/drawable-v24/photo3.png
  app/src/main/res/drawable-v24/photos1.png
  app/src/main/res/drawable/airline_sit.xml
  app/src/main/res/drawable/default_dot.xml
  app/src/main/res/drawable/ic_baseline_free_breakfast_24.xml
  app/src/main/res/drawable/ic_baseline_hot_tub_24.xml
  app/src/main/res/drawable/ic_baseline_room_service_24.xml
  app/src/main/res/drawable/ic_baseline_wifi_12.xml
  app/src/main/res/drawable/ic_favorite_border_white_24dp.xml
  app/src/main/res/drawable/loading_profile_image.png
  app/src/main/res/drawable/round_trip_icon.xml
  app/src/main/res/drawable/selected_dot.xml
  app/src/main/res/drawable/tab_selector.xml
  app/src/main/res/drawable/white_back_arrow.xml
  app/src/main/res/drawable/white_bg_blue_stroke.xml
  app/src/main/res/layout/activity_popular_destination_details.xml
  app/src/main/res/layout/fragment_location_activity_reviews.xml
  app/src/main/res/layout/fragment_popular_destination_details_overview.xml
  app/src/main/res/layout/fragment_popular_destination_details_review.xml
  app/src/main/res/layout/fragment_support.xml
  app/src/main/res/layout/popular_destination_details_recreation_recyclerview_item.xml
  app/src/main/res/layout/popular_destination_recyclerview_hotels_item.xml
  app/src/main/res/layout/popular_destination_reviews_recyclerview_item.xml
  app/src/main/res/layout/support_page_recycler_list_item.xml
  app/src/main/res/layout/view_more_rooms_1.xml
  app/src/main/res/layout/view_more_rooms_recycler_items.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: 1 P, 2 P, 3 P

#310 Fixes #296
  .idea/misc.xml
  app/src/main/java/com/michael/afrivac/MainActivity.java
  app/src/main/java/com/michael/afrivac/model/FindHotel.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelFragment.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelRecyclerAdapter.java
  app/src/main/res/drawable/frame.png
  app/src/main/res/drawable/sliders.png
  app/src/main/res/drawable/tree.png
  app/src/main/res/layout/fragment_find_hotel.xml
  app/src/main/res/layout/item_find_hotel.xml
Labels: 2 P

#314 Test
  .idea/misc.xml
  app/src/main/java/com/michael/afrivac/MainActivity.java
  app/src/main/java/com/michael/afrivac/model/FindHotel.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelFragment.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelRecyclerAdapter.java
  app/src/main/res/drawable/frame.png
  app/src/main/res/drawable/sliders.png
  app/src/main/res/drawable/tree.png
  app/src/main/res/layout/fragment_find_hotel.xml
  app/src/main/res/layout/item_find_hotel.xml
Labels: 2 P

#322 Fixes #229
  app/src/main/java/com/michael/afrivac/model/FindHotel.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelFragment.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelRecyclerAdapter.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelViewModel.java
  app/src/main/res/layout/item_find_hotel.xml
Labels: 3 P

#333 Delete account feature
  app/src/main/java/com/michael/afrivac/Auth/AuthViewModel.java
  app/src/main/java/com/michael/afrivac/model/FindHotel.java
  app/src/main/java/com/michael/afrivac/ui/account/AccountFragment.java
  app/src/main/java/com/michael/afrivac/ui/account/DeleteAccountDialog.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelFragment.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelRecyclerAdapter.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelViewModel.java
  app/src/main/res/layout/fragment_delete_account.xml
  app/src/main/res/layout/item_find_hotel.xml
  app/src/main/res/values/strings.xml
Labels: 3 P

#343 fix conflict
  .idea/misc.xml
  README.md
  app/build.gradle
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsReviewFragment.java
  app/src/main/java/com/michael/afrivac/ReviewDetails.java
  app/src/main/res/layout/activity_forget_password.xml
Labels: 1 P

#349 Final fixes complete
  .idea/gradle.xml
  .idea/misc.xml
  README.md
  app/activity_find_hotel_details_review.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/michael/afrivac/Adapter/DiscoverAdapter.java
  app/src/main/java/com/michael/afrivac/Adapter/PopularAdapter.java
  app/src/main/java/com/michael/afrivac/Auth/AuthViewModel.java
  app/src/main/java/com/michael/afrivac/ContactUsActivity2.java
  app/src/main/java/com/michael/afrivac/FindHotelDetailsReviewActivity.java
  app/src/main/java/com/michael/afrivac/HomePage.java
  app/src/main/java/com/michael/afrivac/LoginActivity.java
  app/src/main/java/com/michael/afrivac/MainActivity.java
  app/src/main/java/com/michael/afrivac/PopularDestinationDetailsReviewFragment.java
  app/src/main/java/com/michael/afrivac/PopularDestinationReviewsRecyclerviewAdapter.java
  app/src/main/java/com/michael/afrivac/ReviewDetails.java
  app/src/main/java/com/michael/afrivac/SplashscreenActivity.java
  app/src/main/java/com/michael/afrivac/WalletPageActivity.java
  app/src/main/java/com/michael/afrivac/model/DiscoverAfrica.java
  app/src/main/java/com/michael/afrivac/model/PopularDestinationReviews.java
  app/src/main/java/com/michael/afrivac/model/PopularPlaces.java
  app/src/main/java/com/michael/afrivac/model/Wallet.java
  app/src/main/java/com/michael/afrivac/ui/findHotel/FindHotelFragment.java
  app/src/main/java/com/michael/afrivac/ui/popular_destination/PopularDestinationFragment.java
  app/src/main/java/com/michael/afrivac/ui/popular_destination/PopularDestinationRVAdapter.java
  app/src/main/java/com/michael/afrivac/ui/support/SupportFragment.java
  app/src/main/res/drawable/rectangle118.png
  app/src/main/res/layout/activity_contact_us2.xml
  app/src/main/res/layout/activity_find_hotel_details_review.xml
  app/src/main/res/layout/activity_forget_password.xml
  app/src/main/res/layout/activity_home_page.xml
  app/src/main/res/layout/activity_wallet_page.xml
  app/src/main/res/layout/fragment_delete_account.xml
  app/src/main/res/layout/fragment_support.xml
  app/src/main/res/layout/layout_discover_africa.xml
  app/src/main/res/layout/layout_populardestination.xml
  app/src/main/res/layout/popular_destination.xml
  app/src/main/res/layout/resend_verification_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: 1 P, 3 P
